# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glinet < Formula
  desc "Console client for GL.Inet routers"
  homepage "https://github.com/kazhuravlev/glinet-cli"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kazhuravlev/glinet-cli/releases/download/v0.7.0/glinet-cli_0.7.0_Darwin_arm64.tar.gz"
      sha256 "67d9b992acc30f7c25ee5a23da3fc7163e94b181a5554bbf2afdb589c65b78fc"

      def install
        bin.install "glinet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazhuravlev/glinet-cli/releases/download/v0.7.0/glinet-cli_0.7.0_Linux_arm64.tar.gz"
      sha256 "ade8f87a84688dfdde715f1b5019de2d13a091d819efe7fc78df6856825b41cc"

      def install
        bin.install "glinet"
      end
    end
  end

  test do
    system "#{bin}/glinet help"
  end
end
