# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glinet < Formula
  desc "Console client for GL.Inet routers"
  homepage "https://github.com/kazhuravlev/glinet"
  version "0.6.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kazhuravlev/glinet/releases/download/v0.6.5/glinet-cli_0.6.5_Darwin_arm64.tar.gz"
      sha256 "7674d02c67e48ea73fc380ddb92615022cbb518bd6b572cfcc20574bd3236b17"

      def install
        bin.install "glinet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazhuravlev/glinet/releases/download/v0.6.5/glinet-cli_0.6.5_Linux_arm64.tar.gz"
      sha256 "54909cab576a3145435f02210d64ae9586acfdcddca08784ec9e74ab6f8a0bfc"

      def install
        bin.install "glinet"
      end
    end
  end

  test do
    system "#{bin}/glinet help"
  end
end
